 SELECT * FROM customer
 LIMIT 10;

-- Q.1 what is the total revenue generated by male vs female customers?
SELECT gender, SUM(purchase_amount) AS revenue
FROM customer
GROUP BY gender;

-- Q.2 Which customers used a discount but still spent more than the average purchase amount?
SELECT customer_id ,purchase_amount
FROM customer
WHERE discount_applied="Yes" AND purchase_amount>=(SELECT AVG(purchase_amount) FROM customer);

-- Q.3 which are the top 5 products with the highest average review rating?
SELECT item_purchased, ROUND(AVG(review_rating),2) as "Average Product Rating"
FROM customer
GROUP BY item_purchased
ORDER BY AVG(review_rating) DESC
LIMIT 5;

-- Q.4 Compare the average purchase amounts b/w standard and express shipping 
SELECT shipping_type, ROUND(AVG(purchase_amount),2) AS "Average purchase amount"
FROM customer
WHERE shipping_type IN ("Standard","Express")
GROUP BY shipping_type;

-- Q.5 DO subscribed customers spend more? Compare average spend and total revenue 
-- between subscribers and non subscriber
SELECT subscription_status, 
COUNT(customer_id),
ROUND(AVG(purchase_amount),2) AS "Average Spend" ,
ROUND(SUM(purchase_amount),2) AS "Total Revenue"
FROM customer
GROUP BY subscription_status;

-- Q.6 which 5 products have the highest percentage of purchases with discounts aplies?
SELECT item_purchased , ROUND(100*SUM(CASE WHEN discount_applied="Yes" THEN 1 ELSE 0 END)/COUNT(*),2) AS discount_rate
FROM customer
GROUP BY item_purchased
order by discount_rate DESC
LIMIT 5;

-- Q.7 Segment customers into new ,returning , and loyal based on their total
-- number of previous purchases ,and show the count of each segment.
WITH customer_type AS(
	SELECT customer_id, previous_purchases,
		CASE 
			WHEN previous_purchases=1 THEN 'New'
			WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
			ELSE 'Loyal'
		END AS customer_segment
	FROM customer
)
SELECT customer_segment,count(*) AS 'Count'
FROM customer_type
GROUP BY customer_segment;

-- Q.8 what are the top 3 purchases products within each category?
with item_rank AS(
	SELECT item_purchased,category,COUNT(customer_id) AS total_orders,
		ROW_NUMBER() OVER (PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS items_rank
	FROM customer
    GROUP BY item_purchased,category 
)
SELECT category,item_purchased,total_orders
FROM item_rank
WHERE items_rank<4;

-- Q.9 Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscriber?
-- SELECT subscription_status,COUNT(customer_id)
-- FROM customer
-- WHERE previous_purchases>5 AND subscription_status='Yes'
SELECT subscription_status,COUNT(customer_id)
FROM customer
WHERE previous_purchases>5
GROUP BY subscription_status;

-- Q.10 What is the revenue contribution of each age group?
SELECT age_group,SUM(purchase_amount) AS Revenue
FROM customer
GROUP BY age_group
ORDER BY Revenue DESC;
